# Header
menu:
  Home: /
  My Works: /works
  About: /about
  #Tags: /tags

rss: /atom.xml

# User Info
user_name: Diskobólos
user_avatar: https://cdn2.iconfinder.com/data/icons/rcons-user/32/male-shadow-circle-512.png
user_location: Earth
user_description: "A Touch Of Zen"
user_contact: haojen.ma@gmail.com
user_introduction: "《掷铁饼者》（希腊语：Δισκοβόλος, 拉丁化：Diskobólos），古希腊雕塑作品，是雕塑家米隆的代表作，完成于古风时期末。原作已失传，通过众多罗曼锡青铜复制品而广为人知。
                    作品描绘了铁饼被摆至最高点即将抛出的一刻，有着强烈的动感，将完美的人体造型和瞬间的动态表现得淋漓尽致。
                    <p>这尊被誉为“体育运动之神”的雕像[1]  ，一望而知是表现投掷铁饼的一个典型瞬间动作：人体动势弯腰屈臂成S型。这使单个的人体富于运动变化，但这种变化常常造成不稳定感，所以作者将人物的重心移至右足，让左足尖点地以支撑辅助，以头为中心两臂伸展成上下对称，从而使不稳定的躯体获得稳定感。身体的正侧转动，下肢的前后分列，既符合掷铁饼的运动规律，又造成单纯中见多样变化的形式美感。
                       运动员之所以呈现出裸体的形态，是由古希腊人的社会风俗所决定的。因为，古希腊人在从事体育运动和宗教性的文艺演出活动时，男子往往赤身裸体。他们认为完美健康的人体乃是人的骄傲，是神性的体现。这种社会风俗反过来也促进了希腊人体雕像的发展，并且形成了西方美术史中崇尚人体美的艺术传统。</p>"

github_username: haojen
twitter_username: ehazon
weibo_username:
zhihu_username: margretz
facebook_username:
linkedin_username:

# Content
excerpt_link: Read More
fancybox: true

# display widgets at the bottom of index pages (pagination == 2)
#index_widgets:
# - category
# - tagcloud
# - archive

# widget behavior
#archive_type: 'monthly'
#show_count: false

# 评论系统
# 不要用别人的 uid, 自己去注册一个吧
use_livere: true
livere_uid: MTAyMC8yOTE4Ni81NzUz

use_disqus: false
disqus_url: https://haojen.disqus.com/embed.js

# Miscellaneous
google_analytics:
favicon: /favicon.png
#twitter:
#google_plus:
#fb_admins:
#fb_app_id:


