# main menu navigation
menu:
  Home: /
  About: /about
  Archive: /archives

widgets:
  - tag
  - archive
  - recent_posts
  - category
  - profile

# social config
social:
  zhihu:
  twitter: /
  facebook: /
  linkedin:
  instagram: /
  github: haojen

user:
  name: Haojen
  avatar:
  location: In the dust
  description: May the Force be with you
  footnotes: # footnotes

# documents: https://github.com/utterance/utterances
# API config: https://utteranc.es/
comment_utteranc:
  enable: true
  repo: Haojen/Claudia-theme-blog # your blog repo


# documents: https://valine.js.org/quickstart.html
comment_valine:
  enable: false
  appId:
  appKey:

comment_disqus:
    enable: false
    url:  # the url of your website main domain like this https://xxx.xxx/
    name: # the short name in disqus

# dark
# light
# user-can-set
appearance: auto # Default value is auto

# Miscellaneous
favicon: images/favicon.ico

friend_links:
  - title: Google
    link: https://www.google.com/
  - title: Github
    link: https://www.github.com/
  - title: V2EX
    link: https://v2ex.com/
  - title: Twitter
    link: https://twitter.com/

# Google Analytics
ga_track_id:
ga_domain:

# Baidu Analytics
ba_track_id:

# picture of about page
about_pic: about.png

image_zoom:
  enable: true